// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSz_u0-drHxCP3v6Kuya5Fa4AZlFob5qY',
    appId: '1:488303431955:web:56e8919fa762f878b98ae6',
    messagingSenderId: '488303431955',
    projectId: 'tcgp-trading',
    authDomain: 'tcgp-trading.firebaseapp.com',
    storageBucket: 'tcgp-trading.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnnsH3EhyWukHn2TCBlcliW7TueuCQC8c',
    appId: '1:488303431955:android:22e9b58b0eff0b53b98ae6',
    messagingSenderId: '488303431955',
    projectId: 'tcgp-trading',
    storageBucket: 'tcgp-trading.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1sWDgCjG_KxbsvOF5ut0RGP4Va3mzk_Y',
    appId: '1:488303431955:ios:293f42fe2f016e9bb98ae6',
    messagingSenderId: '488303431955',
    projectId: 'tcgp-trading',
    storageBucket: 'tcgp-trading.firebasestorage.app',
    iosBundleId: 'com.example.tcgpTradingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1sWDgCjG_KxbsvOF5ut0RGP4Va3mzk_Y',
    appId: '1:488303431955:ios:293f42fe2f016e9bb98ae6',
    messagingSenderId: '488303431955',
    projectId: 'tcgp-trading',
    storageBucket: 'tcgp-trading.firebasestorage.app',
    iosBundleId: 'com.example.tcgpTradingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSz_u0-drHxCP3v6Kuya5Fa4AZlFob5qY',
    appId: '1:488303431955:web:380a020809c8e159b98ae6',
    messagingSenderId: '488303431955',
    projectId: 'tcgp-trading',
    authDomain: 'tcgp-trading.firebaseapp.com',
    storageBucket: 'tcgp-trading.firebasestorage.app',
  );
}
